// PHASE 2 BASELINE — Profile identity regression characterization.
//
// Updated 2026-07-27 (Intelligence-OS audit): this file originally pinned
// `tryBuildManualProfileFastPathAnswer`'s return shape as a synthesized
// final-answer string (`route.answer` matching "I'm Evin...",
// `usedDeterministicFastPath === true`). That contract was DELIBERATELY
// superseded by `ed827532 feat(profile-intelligence): full-JIT final-answer
// hardening` — the function (aliased to `selectManualProfileEvidence`) now
// returns a deterministic EVIDENCE SELECTION (`route.items`,
// `usedDeterministicEvidenceSelection`, `finalGenerationMode: 'jit_llm'`),
// never a pre-baked answer string; `ProfileTreeService.ts`'s own docstring
// says so explicitly ("This service no longer returns deterministic final
// prose; callers must pass this prompt to a provider"). The 9 tests below
// failed against the OLD shape (route.answer was undefined) even though the
// real, current behavior is correct — verified via `buildProfileJitPrompt`,
// the same builder the live manual-chat/WTA paths and ProfileTreeService use
// to render the actual text sent to the provider.
//
// These tests now assert the CURRENT contract: (1) evidence selection is
// still deterministic and still surfaces the real candidate facts, (2) the
// ACTUAL rendered JIT prompt text (what the provider receives) never
// contains an assistant-identity leak and always contains the real facts.
// This is a stricter, more meaningful test than the old one — it checks the
// literal text sent to the LLM, not an intermediate assumption.
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import {
  tryBuildManualProfileFastPathAnswer,
  isAssistantIdentityQuestion,
} from '../../../../dist-electron/electron/llm/manualProfileIntelligence.js';
import { buildProfileJitPrompt } from '../../../../dist-electron/electron/llm/ProfileJitPromptBuilder.js';

const PROFILE = {
  identity: { name: 'Evin John' },
  experience: [{ role: 'AI Engineer', company: 'Acme', bullets: ['Built real-time AI copilots'] }],
  projects: [{ name: 'Natively', description: 'an AI meeting copilot', technologies: ['Electron', 'TypeScript'] }],
  skills: ['TypeScript', 'Python', 'Electron', 'React'],
  education: [{ degree: 'BS', field: 'CS', institution: 'State University' }],
};

const NATIVELY_LEAK = /\bi'?m natively\b|\bi am natively\b|\ban ai assistant\b|\bas an ai\b/i;

// The bug list from the prompt: identity questions must NOT answer "I'm Natively".
const IDENTITY_QUESTIONS = [
  'introduce yourself',
  'who are you?',
  'what is your name?',
  'what is your full name?',
  'what should I call you?',
  'tell me about yourself',
  'walk me through your background',
];

/** Render the actual text the provider would receive for this route, exactly like ProfileTreeService.answer() does. */
function renderJitPrompt(question, route) {
  return buildProfileJitPrompt({
    question,
    answerType: route.answerType,
    answerShape: route.answerShape,
    sourceOwner: route.sourceOwner,
    evidence: route,
    maxAnswerWords: 90,
  }).userPrompt;
}

describe('PHASE2 baseline — profile identity (candidate voice, no Natively leak)', () => {
  for (const q of IDENTITY_QUESTIONS) {
    test(`"${q}" → deterministic evidence selection grounded in the real candidate, never "I am Natively"`, () => {
      const route = tryBuildManualProfileFastPathAnswer({
        question: q, profile: PROFILE, source: 'what_to_answer',
      });
      assert.ok(route, `expected a deterministic evidence-selection route for "${q}"`);
      assert.ok(route.items && route.items.length > 0, `"${q}" selected no evidence items`);
      assert.ok(
        route.items.some((i) => i.field === 'identity.name' && i.value === 'Evin John'),
        `"${q}" must ground on the real candidate's name`,
      );
      const rendered = renderJitPrompt(q, route);
      assert.doesNotMatch(rendered, NATIVELY_LEAK, `"${q}"'s rendered provider prompt leaked assistant identity`);
      assert.match(rendered, /Evin John/, `"${q}"'s rendered provider prompt must reference the candidate`);
    });
  }

  test('identity questions use deterministic evidence selection (facts are pinned; final prose is JIT-generated by design)', () => {
    const route = tryBuildManualProfileFastPathAnswer({
      question: 'what is your name?', profile: PROFILE, source: 'what_to_answer',
    });
    assert.equal(route?.usedDeterministicEvidenceSelection, true);
    assert.equal(route?.finalGenerationMode, 'jit_llm');
    // Full-JIT law (ed827532): the final answer is ALWAYS provider-generated
    // from the deterministically-selected evidence above — this function no
    // longer returns pre-baked prose, by deliberate design, not by omission.
    assert.equal(route?.usedDeterministicFastPath, false);
    const rendered = renderJitPrompt('what is your name?', route);
    assert.match(rendered, /Evin John/);
  });

  test('GENUINE app/assistant questions DO bail to the assistant path', () => {
    for (const q of ['are you an AI?', 'what is Natively?', 'what model are you?', 'are you ChatGPT?', 'who built you?']) {
      assert.equal(isAssistantIdentityQuestion(q), true, `"${q}" should be assistant-meta`);
      // The fast path returns null for assistant-meta → handled by assistant identity logic.
      const route = tryBuildManualProfileFastPathAnswer({ question: q, profile: PROFILE, source: 'manual_input' });
      assert.equal(route, null, `"${q}" must NOT be answered as the candidate`);
    }
  });

  test('candidate identity asks are NOT misclassified as assistant-meta', () => {
    for (const q of ['who are you?', 'what is your name?', 'introduce yourself']) {
      assert.equal(isAssistantIdentityQuestion(q), false, `"${q}" must read as candidate identity when a profile is loaded`);
    }
  });

  test('project listing is deterministic and complete', () => {
    const route = tryBuildManualProfileFastPathAnswer({
      question: 'what are your projects', profile: PROFILE, source: 'what_to_answer',
    });
    assert.ok(route);
    const rendered = renderJitPrompt('what are your projects', route);
    assert.match(rendered, /Natively/);
  });
});
